services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password  --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/schema.sql:/data/application/init.sql"
